version: '3.9'

services:

  backend:
    build: ./backend
    command: make run-api
    volumes:
      - ./backend:/app
    ports:
      - "5001:5000"
    depends_on:
      - db

  db:
    image: "postgres:14.4"
    command: [ "postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: uno
      POSTGRES_DB: uno
      POSTGRES_PASS: uno
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/posgresql/data

volumes:
    db-data:

