"""empty message

Revision ID: 27d605322a40
Revises: 8d0d1a816560
Create Date: 2022-08-15 08:21:25.200599+00:00
"""

import alembic.op as op
import sqlalchemy as sa


revision = '27d605322a40'
down_revision = '8d0d1a816560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'accesstokens', ['token'])
    op.create_unique_constraint(None, 'refreshtokens', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refreshtokens', type_='unique')
    op.drop_constraint(None, 'accesstokens', type_='unique')
    # ### end Alembic commands ###
