"""empty message

Revision ID: 6726269efa0d
Revises: 27d605322a40
Create Date: 2023-04-11 17:03:29.213819+00:00
"""

import alembic.op as op
import sqlalchemy as sa



revision = '6726269efa0d'
down_revision = '27d605322a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
