"""empty message

Revision ID: c46610caca3d
Revises: 6726269efa0d
Create Date: 2023-04-13 12:30:32.488350+00:00
"""

import alembic.op as op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'c46610caca3d'
down_revision = '6726269efa0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accesstokens', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accesstokens', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
